jedi_blades/urls.py
from django.contrib import admin
from django.urls import path
from app.views import LightsaberListView, LightsaberDetailView, CharacterDetailView, TeamView, AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LightsaberListView.as_view(), name='lightsaber-list'),
    path('lightsaber/<int:pk>/', LightsaberDetailView.as_view(), name='lightsaber-detail'),
    path('character/<int:pk>/', CharacterDetailView.as_view(), name='character-detail'),
    path('team/', TeamView.as_view(), name='team'),
    path('about/', AboutView.as_view(), name='about'),
]

app/models.py
from django.db import models
from cloudinary.models import CloudinaryField

class Lightsaber(models.Model):
    name = models.CharField(max_length=100, unique=True)
    color = models.CharField(max_length=20)
    owner = models.ForeignKey('Character', on_delete=models.CASCADE, related_name='lightsaber')
    design = models.CharField(max_length=100)
    description = models.TextField(default='Details about the lightsabers\'s backstory, significant events, and role in the Star Wars universe.')
    image = CloudinaryField('image', default='https://res.cloudinary.com/digqsxx3z/image/upload/v1716572753/DALL_E_2024-05-22_21.57.28_-_An_imposing_landscape_of_a_Sith_stronghold_on_a_barren_volcanic_planet_where_lava_rivers_flow_freely_under_a_stormy_ash-filled_sky._The_stronghold_i_ilacid.webp')

    def __str__(self):
        return f"{self.name} ({self.color})"

class Character(models.Model):
    ALIGNMENT_CHOICES = [
        ('L', 'Light Side'),
        ('D', 'Dark Side'),
    ]

    name = models.CharField(max_length=100, unique=True)
    full_name = models.CharField(max_length=200)
    alignment = models.CharField(max_length=1, choices=ALIGNMENT_CHOICES)
    home_planet = models.CharField(max_length=100)
    profile_image = CloudinaryField('image', default='https://res.cloudinary.com/digqsxx3z/image/upload/v1716572753/DALL_E_2024-05-22_21.57.28_-_An_imposing_landscape_of_a_Sith_stronghold_on_a_barren_volcanic_planet_where_lava_rivers_flow_freely_under_a_stormy_ash-filled_sky._The_stronghold_i_ilacid.webp')
    lore = models.TextField(default='Details about the character\'s backstory, significant events, and role in the Star Wars universe.')
    def __str__(self):
        return self.name

app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from .models import Lightsaber, Character
from django.http import HttpResponse


def home(request):
    return HttpResponse("Welcome to the Jedi Blades app!")


class LightsaberListView(ListView):
    model = Lightsaber
    template_name = 'index.html'  # This is the template we'll use to render the lightsabers page
    context_object_name = 'lightsabers'  # The context object we'll use in the template


class LightsaberDetailView(DetailView):
    model = Lightsaber
    template_name = 'lightsaber_details.html'
    context_object_name = 'lightsaber'

class AboutView(TemplateView):
    template_name = 'about_lightsaber.html'


class TeamView(TemplateView):
    template_name = 'team.html'


class CharacterDetailView(DetailView):
    model = Character
    template_name = 'character_details.html'
    context_object_name = 'character'

app/templates/about_lightsaber.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/about_lightsaber.css' %}" />
<section>
  <h1 class="heading-1">About Lightsabers</h1>
  <p class="text">
    Lightsabers, the iconic weapons of the Jedi and Sith, are more than mere
    blades of energy. These elegant weapons, often referred to as "laser
    swords," are a testament to the craftsmanship, technological prowess, and
    deep connection to the Force required to wield them. Each lightsaber is
    unique, reflecting the personality and skill of its creator. Here, we delve
    into the intricate components that make up a lightsaber and the lore
    surrounding these legendary weapons.
  </p>
  <div class="lightsaber-image-container">
    <img
      src="https://th.bing.com/th/id/OIP.Uj1ZyQOpCIqg0XdSEzuX2gAAAA?rs=1&pid=ImgDetMain"
      alt="Lightsaber Anatomy image"
      class="image-fluid"
    />
    <!-- Add overlay divs for each part of the lightsaber -->
    <div
      class="overlay"
      id="crystal"
      data-info="Kyber Crystal: The heart of the lightsaber, channeling the Force to create the blade."
    ></div>
    <div
      class="overlay"
      id="hilt"
      data-info="Hilt: The handle of the lightsaber, housing all the crucial components."
    ></div>
    <div
      class="overlay"
      id="emitter"
      data-info="Emitter: Projects and controls the blade's length and intensity."
    ></div>
    <div
      class="overlay"
      id="blade"
      data-info="Blade: Projected beam of light used to defeat enemies."
    ></div>
    <!-- Add more overlays as needed -->
  </div>
  <div id="hover-info"></div>
</section>
<section>
  <h2 class="heading-2">History and Lore</h2>
  <p class="text">
    Lightsabers have a storied history in the galaxy. From the legendary battles
    of the Jedi and Sith to the creation of unique lightsabers by their
    wielders, these weapons have always been a symbol of power and skill.
    Notable lightsabers include Anakin Skywalker's blue blade, Darth Vader's red
    saber, and Luke Skywalker's green lightsaber, each with its own tale.
  </p>
</section>
<section>
  <h2 class="heading-2">Construction and Components</h2>
  <p class="text">
    Constructing a lightsaber is a rite of passage for both Jedi and Sith. The
    process involves gathering parts and a Kyber crystal, often through a
    journey of self-discovery. Key components include the hilt, which houses the
    power source and controls, the emitter matrix, and the focusing crystal that
    shapes the blade.
  </p>
</section>
<section>
  <h2 class="heading-2">Types and Variations</h2>
  <p class="text">
    Lightsabers come in various forms to suit the fighting styles of their
    wielders. The double-bladed lightsaber, famously wielded by Darth Maul,
    offers a distinct combat advantage. The crossguard lightsaber, used by Kylo
    Ren, features additional blades for offensive and defensive maneuvers.
    Curved-hilt lightsabers, favored by Count Dooku, provide ergonomic benefits
    for dueling.
  </p>
</section>
<section>
  <h2 class="heading-2">Famous Lightsaber Battles</h2>
  <p class="text">
    Throughout history, lightsabers have been at the center of many legendary
    battles. From the duel between Obi-Wan Kenobi and Anakin Skywalker on
    Mustafar to the clash between Rey and Kylo Ren, these epic encounters have
    shaped the fate of the galaxy.
  </p>
</section>

<script src="{% static 'js/about.js' %}"></script>
{% endblock %}

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Jedi Blades</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <script
      src="https://kit.fontawesome.com/11665d5c0d.js"
      crossorigin="anonymous"
    ></script>
    <link
      rel="shortcut icon"
      href="{% static 'images/favicon/favicon.ico' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body class="p-0 m-0">
    <!-- Cursor Lightsaber -->
    <div class="cursor">
      <div class="lightsaber">
        <div class="glow"></div>
        <div class="core"></div>
        <div class="handle"></div>
      </div>
    </div>
    <!-- Navbar for medium to large screens: Always expanded -->
    <header class="container-max">
      <nav class="navbar navbar-expand-md navbar-dark">
        <div class="container-fluid py-3">
          <a class="navbar-brand sfx" href="/"
            ><img
              src="https://res.cloudinary.com/digqsxx3z/image/upload/v1716671824/q3oqyzmvtog2wrw8zh9v.png"
              alt="Lightsabers"
              class="nav-logo"
            />JediBlades</a
          >
          <button id="toggle-music" class="btn btn-warning sfx" aria-label="Play Star Wars music.">
            <i class="fa-solid fa-volume-xmark"></i>
          </button>
          <div class="navbar">
            <ul class="navbar-nav w-100 justify-content-around">
              <li class="nav-item sfx">
                <a
                  class="nav-link sfx {% if request.resolver_match.url_name == 'team' %}active{% endif %}"
                  href="{% url 'team' %}"
                >
                  <img
                    src="https://res.cloudinary.com/digqsxx3z/image/upload/v1716671824/dxhe7dl6mgwsgoxigk0e.png"
                    alt="Team"
                    class="nav-logo"
                  />
                  <span>Team</span>
                </a>
              </li>
              <li class="nav-item sfx">
                <a
                  class="nav-link sfx {% if request.resolver_match.url_name == 'about' %}active{% endif %}"
                  href="{% url 'about' %}"
                >
                  <img
                    src="https://res.cloudinary.com/digqsxx3z/image/upload/v1716671824/q3oqyzmvtog2wrw8zh9v.png"
                    alt="about_lightsaber"
                    class="nav-logo"
                  />
                  <span>About Blades</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}
      <!-- Page-specific content will go here -->
      {% endblock %}
      <!-- Cookie Consent Modal -->
      <div
        class="modal fade"
        id="cookieConsentModal"
        tabindex="-1"
        aria-labelledby="cookieConsentModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="cookieConsentModalLabel">
                Cookie Consent
              </h5>
            </div>
            <div class="modal-body">
              By clicking outside of this cookie modal , you agree to the use of
              cookies to enhance your browsing experience. Cookies are small
              pieces of information that are held on your local device for a
              specified time . These can be used to track your personal data in
              our case third party cookies are used by cloudinary the provider
              of our free image hosting . Please visit their cookie policy for
              more information and do not hesitate to reach out to us with any
              questions you might have. Clicking outside of the cookie display
              will also enable sound effects and by continuing this will be
              taken as permission to play them.
            </div>
          </div>
        </div>
      </div>
      <!-- Copyright policy  -->
      <div
        class="modal fade border-dark"
        id="policyModal"
        tabindex="-1"
        role="dialog"
        aria-labelledby="policyModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content text-black bg-light">
            <div class="modal-header">
              <h5 class="modal-title" id="policyModalLabel">
                Jedi Blade Copyright and Trademark Policy
              </h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <h5>1. Ownership and Intellectual Property Rights</h5>
              <p>
                "Star Wars" and its related entities, including the films "Star
                Wars: Episode I - The Phantom Menace," "Star Wars: Episode II -
                Attack of the Clones," etc., and all logos, characters, artwork,
                names, and other elements are the sole property of Lucasfilm
                Limited.
              </p>

              <h5>2. Affiliation Disclaimer</h5>
              <p>
                Jedi Blade is not affiliated with, endorsed by, or connected to
                Lucasfilm Limited or any of its subsidiaries.
              </p>

              <h5>3. Usage of Copyrighted and Trademarked Material</h5>
              <p>
                The use of "Star Wars" trademarks by Team Jedi Blade is for
                referential purposes only during the hackathon and strictly
                non-commercial.
              </p>

              <h5>4. Provisions for Hackathon Participants</h5>
              <p>
                Participants are encouraged to use "Star Wars" themes creatively
                and responsibly, ensuring no implication of official
                endorsement.
              </p>

              <h5>5. Copyrighted Material Usage Policy</h5>
              <p>
                Materials used are for personal, non-commercial purposes only,
                with proper attribution to the copyright holders.
              </p>

              <h5>6. Compliance with Copyright Law</h5>
              <p>
                Adherence to the UK Copyright, Designs and Patents Act 1988 and
                the US Copyright Act of 1976 is mandatory.
              </p>

              <h5>7. Policy Enforcement</h5>
              <p>
                Non-compliance may lead to disqualification and legal actions by
                the rights holders.
              </p>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
                aria-label="Close"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- Terms of use  -->
      <div
        class="modal fade"
        id="termsModal"
        tabindex="-1"
        role="dialog"
        aria-labelledby="termsModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content text-black bg-light">
            <div class="modal-header">
              <h5 class="modal-title" id="termsModalLabel">Terms of Use</h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <h5>Welcome to Our Website</h5>
              <p>
                By accessing this website, you are agreeing to be bound by these
                website Terms and Conditions of Use, all applicable laws and
                regulations, and agree that you are responsible for compliance
                with any applicable local laws. If you do not agree with any of
                these terms, you are prohibited from using or accessing this
                site.
              </p>

              <h5>Use License</h5>
              <p>
                Permission is granted to temporarily download one copy of the
                materials (information or software) on this site for personal,
                non-commercial transitory viewing only. This is the grant of a
                license, not a transfer of title, and under this license you may
                not:
              </p>
              <ul>
                <li>modify or copy the materials;</li>
                <li>
                  use the materials for any commercial purpose, or for any
                  public display (commercial or non-commercial);
                </li>
                <li>
                  attempt to decompile or reverse engineer any software
                  contained on this website;
                </li>
                <li>
                  remove any copyright or other proprietary notations from the
                  materials; or
                </li>
                <li>
                  transfer the materials to another person or "mirror" the
                  materials on any other server.
                </li>
              </ul>
              <p>
                This license shall automatically terminate if you violate any of
                these restrictions and may be terminated by the website at any
                time. Upon terminating your viewing of these materials or upon
                the termination of this license, you must destroy any downloaded
                materials in your possession whether in electronic or printed
                format.
              </p>

              <h5>Disclaimer</h5>
              <p>
                The materials on this website are provided "as is". The website
                makes no warranties, expressed or implied, and hereby disclaims
                and negates all other warranties, including without limitation,
                implied warranties or conditions of merchantability, fitness for
                a particular purpose, or non-infringement of intellectual
                property or other violation of rights.
              </p>

              <h5>Limitations</h5>
              <p>
                In no event shall the website or its suppliers be liable for any
                damages (including, without limitation, damages for loss of data
                or profit, or due to business interruption,) arising out of the
                use or inability to use the materials on this website, even if
                the website or a website authorized representative has been
                notified orally or in writing of the possibility of such damage.
              </p>

              <h5>Governing Law</h5>
              <p>
                Any claim relating to the website's use is governed by the laws
                of the website's home jurisdiction without regard to its
                conflict of law provisions.
              </p>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer>
      <div class="container footer-content">
        <div class="footer-column">
          <h5 class="footer-title">© 2024 Jedi Blades. All rights reserved.</h5>
        </div>
        <div class="footer-column">
          <h5 class="footer-title">Our Team</h5>
          <a href="{% url 'team' %}#jesse" class="footer-link sfx"
          aria-label="See the team member">Jesse Ross </a><br />
          <a href="{% url 'team' %}#emil" class="footer-link sfx"
             aria-label="See the team member">Emil Jädersten </a><br />
          <a href="{% url 'team' %}#johnny" class="footer-link sfx"
             aria-label="See the team member">Johnny Trinh</a><br />
          <a href="{% url 'team' %}#salma" class="footer-link sfx"
             aria-label="See the team member">Salma Ahmed</a>
        </div>
        <div class="footer-column">
          <h5 class="footer-title">Legal</h5>
          <a
            href="#"
            class="footer-link sfx"
            data-toggle="modal"
            data-target="#termsModal"
            >Terms of Use </a
          ><br />
          <a
            href="#"
            data-toggle="modal"
            data-target="#policyModal"
            class="footer-link sfx"
            >Copyright and Trademark Policy </a
          ><br />
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script></script>
  </body>
</html>

app/templates/character_details.html
{% extends 'base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/character-detail.css' %}" />

<div class="stars-wrapper" id="stars-wrapper"></div>

<div class="container">
  <div class="header-section text-center py-4 fade-in">
    <h1 class="m-4">{{ character.name }}</h1>
  </div>
  <div class="container">
    <div class="content-section">
      <div class="row d-flex justify-content-center">
        <div class="col-10 col-md-6 col-lg-5 sub-section slide-in-left">
          <img
            src="{{ character.profile_image.url }}"
            alt="{{ character.full_name }}"
            class="img-fluid"
          />
        </div>
        <div class="col-12 col-md-10 col-lg-6">
          <div class="sub-section py-5 slide-in-right">
            <div class="card-body text-center">
              <p class="my-2 py-2 txt-xl">
                Alignment:
                <span class="text-white"
                  >{{ character.get_alignment_display }}</span
                >
              </p>
              <p class="my-2 py-2 txt-l">
                Home Planet:
                <span class="text-white">{{ character.home_planet }}</span>
              </p>
              <p class="my-2 py-2 txt-l">
                Lightsaber:
                {% for lightsaber in character.lightsaber.all %}
                <a class="sfx" href="/lightsaber/{{ lightsaber.pk }}" aria-label="View this character's lightsaber.">{{ lightsaber.name }}</a>
                {% endfor %}
              </p>
            </div>
          </div>
        </div>
        <div class="col-10 col-md-10 col-lg-8">
          <div
            class="content-section text-center glass-card py-3 p-1 p-md-3 fade-in"
          >
            <h3 class="my-2 py-2">Character Lore</h3>
            <p class="text-white">{{ character.lore }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/details.js' %}"></script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />

<!-- Content Block -->
<section class="outer-hero-section starry-sky">
  <div class="jedi-hero-section">
    <div class="jedi-hero-text">
      <!-- Content for scrolling effect -->
      <div>
        <h1 class="hero-header">Welcome to Jedi Blades</h1>
        <p>
          Jedi Blades is the place to be for lightsaber enthusiasts. We have a wide
          selection of lightsabers for you to choose from. Whether you are a
          Jedi or a Sith, we have all the lightsabers you could dream of.
        </p>
        <p>
          In our lightsaber gallery, you'll find information about all your favorite lightsabers and their wielders.
          Choose your path and find the lightsaber that speaks to you, or simply take them all in.
        </p>
        <p>
          So come on in and take a look at our collection. May the Force be with
          you!
        </p>
      </div>
    </div>
    <div class="jedi-hero-overlay"></div>
  </div>
</section>
<section class="select-your-side w-100">
  <div
    class="mx-auto d-flex justify-content-center"
    style="z-index: 80 !important"
  >
    <!-- Star Wars Theme Title -->
    <div class="toggle-section pt-4 my-3">
      <div class="text-center mb-3">
        <h2 class="star-wars-title">Choose Your Path</h2>
      </div>
      <!-- Toggle for Jedi, Balance, and Sith -->
      <div
        class="btn-group toggle-buttons"
        role="group"
        aria-label="Sides of the Force"
      >
        <button type="button" class="btn toggle-btn sfx" id="lightSide" aria-label="Light side">
          Jedi
        </button>
        <button type="button" class="btn toggle-btn sfx" id="bothSides" aria-label="Both sides">
          Balance
        </button>
        <button type="button" class="btn toggle-btn sfx" id="darkSide" aria-label="Dark Side">
          Sith
        </button>
      </div>
    </div>
  </div>
  <div class="my-3 row d-flex justify-content-center align-items-center">
    <!-- Content for selected side -->
    <div
      id="sideContent"
      class="row d-flex justify-content-center align-items-center"
    >
      <div class="col-10 col-md-8 d-flex justify-content-center text-center">
        <img id="sideLogo" src="" alt="Side Logo" style="display: none" />
      </div>
      <div class="col-10 col-md-8 d-flex justify-content-center text-center">
        <p id="sideText" class="mt-3" style="display: none"></p>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center mt-3">
      <!-- Render lightsabers from models -->
      {% for lightsaber in lightsabers %}
      <article
        class="col-12 col-md-6 col-lg-4 mb-3 {{ lightsaber.owner.alignment }}"
      >
        <div
          class="card lightsaber-card"
          style="border-color: {{ lightsaber.color }};"
        >
          <div class="card-body row px-4">
            <div class="col-12 col-lg-6">
              <h3 class="card-title">{{ lightsaber.name }}</h3>
              <p class="card-text">
                Color:
                <span style="color: {{ lightsaber.color }};"
                  >{{ lightsaber.color }}</span
                >
              </p>
              <p class="card-text">Owner: {{ lightsaber.owner }}</p>
            </div>
            <div class="col p-2 pb-4 my-4 saber-container d-flex">
              <img
                src="{{ lightsaber.image.url }}"
                alt="{{ lightsaber.name }} Lightsaber"
                class="img-fluid"
              />
            </div>
            <div class="row g-0 justify-content-around px-2">
              <div class="col-10">
                <a
                  href="{% url 'lightsaber-detail' pk=lightsaber.id %}"
                  class="btn btn-primary w-100 sfx"
                  style="border-color: {{ lightsaber.color }};"
                >
                  Details
                </a>
              </div>
              <div class="col-10 py-2">
                <a
                  href="{% url 'character-detail' pk=lightsaber.owner.id %}"
                  class="btn btn-secondary w-100 sfx"
                  style="border-color: {{ lightsaber.color }};"
                >
                  {{ lightsaber.owner.name }}
                </a>
              </div>
            </div>
          </div>
        </div>
      </article>
      {% endfor %}
    </div>
  </div>
</section>
<script src="{% static 'js/index.js' %}"></script>

{% endblock %}

app/templates/lightsaber_details.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/lightsaber-detail.css' %}" />

<div class="starry-sky" id="stars-wrapper">
  <div class="lightsaber-container">
    <div class="header-section text-center py-4 fade-in">
      <h1 class="title1">{{ lightsaber.name }}</h1>
    </div>
    <div class="container">
      <div class="content-section">
        <div class="row d-flex justify-content-center">
          <div class="col-10 col-md-6 lightsaber-image slide-in-left">
            <div class="glass-card">
              <img
                src="{{ lightsaber.image.url }}"
                alt="{{ lightsaber.name }} Lightsaber"
                class="img-fluid"
              />
            </div>
          </div>
          <div class="col-10 col-md-6 slide-in-right">
            <div class="sub-section">
              <div class="glass-card">
                <div class="card-body text-center">
                  <div class="my-3">
                    <h2 class="text-center my-2 txt-xl">
                      Wielded by
                      <a href="/character/{{ lightsaber.owner.pk }}" class="text sfx"  aria-label="View this character's lightsaber.">{{ lightsaber.owner.name }}</a>
                    </h2>
                    <div class="col text-center saber-container">
                      <div class="lightsaber">
                        <div
                          class="glow"
                          style="background-color: {{ lightsaber.color }};"
                        ></div>
                        <div class="core"></div>
                        <div class="handle"></div>
                      </div>
                    </div>
                    <hr class="hr" />
                  </div>
                  <h3 class="py-2 text-center title">
                    Design
                    <span
                      class="d-inline-block rounded-circle"
                      style="width: 20px; height: 20px; background-color: {{ lightsaber.color }};"
                    ></span>
                  </h3>
                  <p class="py-2 text">{{ lightsaber.design }}</p>
                </div>
                
                </div>
                <div
                  class="content-section text-center glass-card py-3 p-1 p-md-3 fade-in"
                >
                  <h3 class="py-2 text-center title">Lightsaber Lore</h3>
                  <p class="py-2 text">{{ lightsaber.description }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="{% static 'js/details.js' %}"></script>
  {% endblock %}
</div>